### ISSUE TITLE
Automated upload of intro2astro project results into Google sheets 

### ISSUE THREAD

**Issue by trouille** [zooniverse/intro2astro-server#3]
Pre-populating Google sheets with the outputs from #2 so that intro2astro instructors can then show and manipulate their classroom's results to their students in class. 

- zooniverse.org/projects/srallen/galaxy-zoo-in-astronomy-101
- zooniverse.org/projects/srallen/intro2astro-hubbles-law

https://docs.google.com/spreadsheets/d/1k2cq0Xec9dXBWwXdZq2m9WQYtDPfRA6e3qvzQY6oDLQ/edit?usp=sharing is an example Google sheet from Tommy when at UMN. Will want to pre-populate with info shown in all these tabs, except not the Charts tab.

https://docs.google.com/spreadsheets/d/1VzJxp2LfWhvClymxATZVuHEtYi0Uf_cIs_yEkePiYAk/edit?usp=sharing is an example Google sheet from the intro2astro-hubbles-law activity from Cody. Will want to pre-populate with these columns in the first tab (Galaxy ID	N Class	RA	Dec	Dist	lambda_av	lambda_err) and not include the 2nd 'Charts' tab. 

In order to include this additional metadata in the Google sheet, be sure to include it in the metadata.csv file for the subject sets in each project. Then in the aggregation export, this additional metadata can be uploaded along at the same time. Note: Tommy & Julie.

**Comment by srallen** [comment]
Closing in favor of zooniverse/rfc#23
