### ISSUE TITLE
Activity 1: hometown data, students input responses and have view-only access

### ISSUE THREAD

**Issue by trouille** [zooniverse/intro2astro-server#4]
This may already be completed effort, so please close if this is the case. 

- Ability for students to input their hometown information (through a web form, or other setup, which will address the issue of students not being able to post unwelcome material)
- Each intro2astro course will have its own Google sheet showing those students' responses. 
- The Google sheet the instructor shows at the front of the class for this activity will be read-only, to avoid unwelcome posts/pics. 

Note: Each classroom will have a unique Google sheet. 

For small classrooms, two options to consider for including existing additional student data:
- have them copy/paste from a template to add to bottom of sheet
- click a button and automatically populate from existing student data.

**Comment by trouille** [comment]
Also here: https://github.com/zooniverse/intro-2-astro/issues/12

**Comment by trouille** [comment]
Since it's going to be a unique database for each classroom, we don't need to worry about this:

Think about including a check on whether the single database sheet has hit the million cell limit. If it does, send an alert to us.

**Comment by trouille** [comment]
Based on 6/1/17 meeting:
We're going to create a Zooniverse project to ingest the answers for the questions for activity 1. Then set up a script to take the answers and output them into a Google sheet. 

Each classroom will have a unique Google sheet for those student's answers.

**Comment by srallen** [comment]
Activity one will use a project instead of a web form.
